#!/bin/sh
set -e
set -u

cat >ci/vars <<-EOF
export VERSION=3.3.12-r0
export BUILD_DATE=$(date +%Y%m%dT%H%M)
export VCS_REF=$(git rev-parse --short HEAD)
export TAG=\${VERSION}_\${BUILD_DATE}_git_\${VCS_REF}
export CI_BUILD_URL=${CIRCLE_BUILD_URL:-none}
EOF
. ci/vars

docker-compose build
