#!/bin/bash
set -e
set -u
. ci/vars

# shellcheck disable=SC2154
docker login -u "${user}" -p "${pass}"
docker-compose push
docker logout

curl -X POST 'https://hooks.microbadger.com/images/jumanjiman/etcd/PiUTzCORtCxitaRI-eMF8Na2c8A='
